name: Image build and push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: mobilenativedeveloper
          password: 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
          registry: docker.pkg.github.com
          repository: mobilenativedeveloper/openai_server/openai_server
          tag_with_ref: true