name: Image build and push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: artemcodelab
          password: 88dtwGb&11175087
          registry: docker.pkg.github.com
          repository: artemcodelab/openai_server/openai_server
          tag_with_ref: true